
window.addEventListener('error',e=>{document.getElementById('loginError').textContent=e.message});
const $=id=>document.getElementById(id);let mode='match',initialized=false,catalog={matches:[],courts:[]},catalogVersion=0,polling=false;
async function api(path,body){const response=await fetch(path,{cache:'no-store',...(body===undefined?{}:{method:'POST',headers:{'Content-Type':'application/json','X-Scoreboard-Request':'1'},body:JSON.stringify(body)})});const value=await response.json();if(!response.ok){if(response.status===401)lock();throw Error(value.error||'Request failed')}return value}
function lock(){initialized=false;$('app').hidden=true;$('login').hidden=false;$('logout').hidden=true}
function option(select,value,label){const item=document.createElement('option');item.value=value;item.textContent=label;select.append(item)}
function chooseMode(value){mode=value;document.querySelectorAll('[data-mode]').forEach(b=>b.setAttribute('aria-pressed',b.dataset.mode===mode));$('sourceFields').hidden=['logo','blank'].includes(mode);$('matchFields').hidden=mode!=='match';$('courtFields').hidden=mode==='match'}
function title(m){return `${m.teamA?.name||'TBD'} vs ${m.teamB?.name||'TBD'}`}
function fillCatalog(courtValue){$('court').replaceChildren();option($('court'),'','All courts');catalog.courts.forEach(c=>option($('court'),c.id,`${c.venueName?c.venueName+' · ':''}${c.name}`));$('court').value=courtValue||'';$('match').replaceChildren();option($('match'),'','Enter a match ID below');catalog.matches.forEach(m=>option($('match'),m.id,`${title(m)} · ${m.status||'Scheduled'}`));$('match').value=$('matchId').value;$('catalogNote').textContent=`${catalog.matches.length} matches · ${catalog.courts.length} courts${!catalog.courts.length?' — this schedule has no assigned court IDs.':''}`}
async function loadCatalog(courtValue=''){const serial=++catalogVersion;$('catalogNote').textContent='Loading schedule…';try{const result=await api('/api/catalog?tournament='+encodeURIComponent($('tournament').value));if(serial!==catalogVersion)return;catalog=result;fillCatalog(courtValue)}catch(e){if(serial===catalogVersion){catalog={matches:[],courts:[]};fillCatalog('');$('catalogNote').textContent=e.message}}}
async function init(state){const c=state.config;chooseMode(c.mode);$('matchId').value=c.match_id;$('brightness').value=Math.round(c.brightness*100);$('brightnessValue').textContent=$('brightness').value+'%';if(!Array.from($('timezone').options).some(o=>o.value===c.timezone))option($('timezone'),c.timezone,c.timezone);$('timezone').value=c.timezone;try{const list=await api('/api/tournaments');$('tournament').replaceChildren();option($('tournament'),'','Public standalone matches');list.tournaments.forEach(t=>option($('tournament'),t.id,t.name));if(c.tournament_id&&!Array.from($('tournament').options).some(o=>o.value===c.tournament_id))option($('tournament'),c.tournament_id,c.tournament_id);$('tournament').value=c.tournament_id;await loadCatalog(c.court_id)}catch(e){$('catalogNote').textContent=e.message}}
async function refreshStatus(){if(polling)return;polling=true;try{const s=await api('/api/status');$('app').hidden=false;$('login').hidden=true;$('logout').hidden=false;$('connection').textContent=s.frame_age!==null&&s.frame_age<3?'Pi connected · display running':'Pi connected · starting';$('activeMode').textContent={match:'Match scoreboard',court:'Automatic court',schedule:'Schedule',logo:'Y-Sports logo',blank:'Blank'}[s.config.mode];$('activeTeams').textContent=s.match?s.match.teams.map(t=>t.name).join(' vs '):'—';$('activeStatus').textContent=s.match?.status||'Ready';$('activeId').textContent=s.active_match_id||'—';$('runtimeError').textContent=s.hardware_error||s.error||'';$('preview').src='/api/preview.png?t='+Date.now();if(!initialized){initialized=true;await init(s)}}catch(e){if(initialized){$('connection').textContent='Pi connection lost';$('runtimeError').textContent=e.message}}finally{polling=false}}
const login=async e=>{e.preventDefault();try{await api('/api/login',{pin:$('pin').value});$('pin').value='';$('loginError').textContent='';await refreshStatus()}catch(e){$('loginError').textContent=e.message}};
$('logout').onclick=async()=>{try{await api('/api/logout',{});lock()}catch(e){$('runtimeError').textContent=e.message}};
document.querySelectorAll('[data-mode]').forEach(b=>b.onclick=()=>{chooseMode(b.dataset.mode);$('feedback').textContent='Not applied yet';});
$('tournament').onchange=()=>loadCatalog();$('refresh').onclick=()=>loadCatalog($('court').value);$('match').onchange=()=>{$('matchId').value=$('match').value};$('brightness').oninput=()=>{$('brightnessValue').textContent=$('brightness').value+'%'};
const applySettings=async e=>{e.preventDefault();$('apply').disabled=true;$('feedback').classList.remove('error');$('feedback').textContent='Applying…';try{await api('/api/config',{mode,match_id:$('matchId').value.trim(),tournament_id:$('tournament').value,court_id:mode==='match'?'':$('court').value,brightness:Number($('brightness').value)/100,timezone:$('timezone').value});$('feedback').textContent='Saved. Display updated.';await refreshStatus()}catch(e){$('feedback').classList.add('error');$('feedback').textContent=e.message}finally{$('apply').disabled=false}};
$('loginForm').onsubmit=login; document.querySelector('#loginForm button').onclick=login;
$('settings').onsubmit=applySettings; $('apply').onclick=applySettings;
refreshStatus();setInterval(()=>{if(initialized)refreshStatus()},1500);
